Add ci workflow
line/create-liff-app pull request #31
Opened 2024-10-28 05:52 UTC by shogo0421

Closes  https://github.com/line/create-liff-app/issues/16

feat: add ci/cd workflow
fix: update react template

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [GitHub Issue](https://github.com/line/create-liff-app/issues).
- [ ] Filled out test instructions.

## 📝 Test Instructions:
install both react/react-ts templates and see if there is no lint / ts error.

2024-10-28 06:12 UTC, shogo0421 commented on templates/react-ts/src/main.tsx
> -ReactDOM.render(
ReactDOM.render is deprecated.
This file follow the file generated by the create-vite command.

https://github.com/vitejs/vite/blob/main/packages/create-vite/template-react-ts/src/main.tsx

2024-10-28 06:18 UTC, shogo0421 commented on package.json
> +    "fix:format": "prettier --write .",
Can I format all files and commit in this PR?

2024-10-28 07:32 UTC, shogo0421 commented on .github/workflows/code-check.yml
> +name: Check code health
ref: [workflow in line/liff-inspector](https://github.com/line/liff-inspector/blob/main/.github/workflows/code-check.yml)

This workflow is not currently running in this repository.
However, it is running in my forked repository, and there are no errors.
https://github.com/shogo0421/create-liff-app/actions/runs/11548918674

[github docs (about-workflow-runs-from-public-forks)](https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-workflow-runs/approving-workflow-runs-from-public-forks#about-workflow-runs-from-public-forks)

> workflows on pull requests to public repositories from some outside contributors will not run automatically, and might need to be approved first. By default, all first-time contributors require approval to run workflows.

2024-10-28 08:11 UTC, shogo0421 commented
@so99ynoodles 
Thank you for creating this CLI tools!
When you have a moment, could you please review my Pull Request?

2025-01-08 10:30 UTC, odanado requested changes

2025-01-08 10:30 UTC, odanado commented on templates/react-ts/src/main.tsx
> -ReactDOM.render(
Thank you for your suggestion.

We would like to avoid making multiple changes to a single pull request.
Could you create a separate pull request for React?

2025-01-23 04:44 UTC, shogo0421 commented
@odanado 
> Could you create a separate pull request for React?

I did it. could you please review my Pull Request? https://github.com/line/create-liff-app/pull/43

2025-02-04 09:49 UTC, odanado commented
@shogo0421 Thank you for your work. Could you resolve the conflict before the review?

2025-02-25 04:11 UTC, odanado commented on .github/workflows/code-check.yml
> +        run: yarn run lint
```suggestion
        run: yarn run lint:eslint
```

2025-02-27 06:30 UTC, odanado approved these changes
LGTM!Thank you!

2025-02-27 06:31 UTC, merged